language: python

install:
 - python setup.py sdist
 - pip install dist/pursue-`python setup.py --version`.tar.gz
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt

script:
 - mamba
